# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7968b245a20ee44d81a5f18d8eefb0df59e87ba4242613feea4a29365f6f3bf02e72625bc10284b7b004d4c9e69ab7bd9930462f11939702988285187192d792

test:
  secret_key_base: 54ce9ad39cbffd36925252213871f6a11a02192522d9f9b6768570b76d56f3ebd57fd52b6c57679185ae48f5007b980f179e3f65f5181396bd59ed1ef78b44d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6a020d72cfbb6ed0957b5b22dca42f493b37f9d407d0b77815498707bd6c65a4c31d3469c47c0f533e0f18f4dfeb3a115d95c61ee4810310feac9bdea13c44e9
